server:
  port: 8888
spring:
  mail:
    protocol: smtps
    host: smtp.qq.com  #qq邮件服务器地址 有其他地址
    username: 2825557671@qq.com #发件人邮箱
    password: cruijgsqyshtdcii #授权码
    default-encoding: UTF-8 #邮件登录字符集编码
    port: 465 #发件人邮件服务器端口

    properties:
      mail:
        stmp:
          ssl:
            enable: true
  redis:
    host: 175.178.6.100
    port: 6379
    password: 153280
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #设置缓存有效期
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\java\idea\reggie_take_out\img\




